(() => {
  'use strict';
  const PREF_KEY='ammr-dashboard-ui-v1',VISIBLE_MS=1000,HIDDEN_MS=4000,TIMEOUT_MS=2500;
  const $=id=>document.getElementById(id), S={data:null,connected:false,timer:0,inflight:false,repoll:false,streamTimers:{},streamRetry:{color:1000,depth:1000},streamBlocked:{color:0,depth:0},mapImage:null,mapKey:''};
  const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{}, arr=v=>Array.isArray(v)?v:[], live=v=>v?.live===true;
  const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
  const num=(v,d=1)=>finite(v)?Number(v).toFixed(d):'—';
  const txt=(id,v)=>{const e=$(id);if(e)e.textContent=v==null||v===''?'—':String(v)};
  const unit=(o,v,u,d=1)=>live(o)&&finite(v)?`${num(v,d)} ${u}`:'—';
  const age=o=>live(o)?`수신 ${num(o.age_s,1)}초 전`:finite(o?.age_s)?`지난 값 · ${num(o.age_s,1)}초 전`:'미수신';
  const scalar=v=>v==null||v===''?'—':typeof v==='object'?String(v.state??v.status??v.action??'—'):String(v);

  function loadPrefs(){let p={view:'full',sections:{}};try{p={...p,...JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}}catch(_){/* 기본값 */}$('view-mode').value=p.view==='compact'?'compact':'full';$('app-shell').classList.toggle('compact',$('view-mode').value==='compact');document.querySelectorAll('details[data-pref]').forEach(d=>{if(typeof p.sections?.[d.dataset.pref]==='boolean')d.open=p.sections[d.dataset.pref];d.addEventListener('toggle',savePrefs)})}
  function savePrefs(){const sections={};document.querySelectorAll('details[data-pref]').forEach(d=>{sections[d.dataset.pref]=d.open});localStorage.setItem(PREF_KEY,JSON.stringify({view:$('view-mode').value,sections}))}
  function duration(v){if(!finite(v))return'—';const n=Math.max(0,Math.floor(Number(v))),d=Math.floor(n/86400),h=Math.floor(n%86400/3600),m=Math.floor(n%3600/60);return d?`${d}일 ${h}시간`:h?`${h}시간 ${m}분`:`${m}분`}
  function cmd(v,allowOld=false){if(!live(v)&&!allowOld)return'—';if(!finite(v?.linear_mps)&&!finite(v?.angular_rps))return'—';return`${num(v.linear_mps,3)} m/s · ${num(v.angular_rps,3)} rad/s · ${age(v)}`}
  function ko(v){const raw=String(v??'—'),key=raw.toUpperCase();return({STOP:'정지',SLOWDOWN:'감속',DO_NOTHING:'보호 개입 없음',EXECUTING:'실행 중',ARMED:'접근 실행 중',ABORTED:'중단됨',SUCCEEDED:'완료',FAILED:'실패',CANCELED:'취소',CANCELLED:'취소',IDLE:'대기',BLOCKED:'차단',READY:'출발 대기',UNKNOWN:'확인 불가',ACTIVE_EVENT_UNSEEN:'감시 활성 · 이벤트 미수신'})[key]??raw}
  function blockerLabel(v){const raw=String(v);if(raw.includes('physical_validation'))return'실물 보정 검증 미완료';return({charger_unplugged_not_confirmed:'충전 분리 확인 대기',perception_stale:'인지 데이터 지연',perception_observation_invalid:'박스 관측 조건 미충족',collision_monitor_intervention:'충돌 보호 정지',command_stale:'속도 응답 지연',odom_stale:'주행 측정 지연',scan_stale:'라이다 지연',battery_voltage_low_or_invalid:'배터리 전압 확인 필요',graph_snapshot_stale:'ROS 연결 정보 지연',collision_monitor_enable_unconfirmed:'충돌 감시 활성 확인 대기',final_zero_not_observed:'정지 명령 확인 대기'})[raw]??raw}
  function perceptionText(v){if(!live(v))return'—';const bits=[];if(typeof v.detected==='boolean')bits.push(v.detected?'감지됨':'미감지');if(typeof v.stable==='boolean')bits.push(v.stable?`안정 ${num(v.stable_frame_count,0)}프레임`:'불안정');if(finite(v.front_distance_m))bits.push(`전방 ${num(v.front_distance_m,2)} m`);if(finite(v.edge_angle_deg))bits.push(`경계 ${num(v.edge_angle_deg,1)}°`);if(finite(v.source_age_s))bits.push(`원본 ${num(v.source_age_s,1)}초 전`);if(finite(v.processing_duration_s))bits.push(`처리 ${num(v.processing_duration_s*1000,0)} ms`);return bits.join(' · ')||age(v)}
  function tag(e,label,tone=''){e.textContent=label;e.className=`tag${tone?` ${tone}`:''}`}

  // These descriptions identify configured responsibilities, not runtime health.
  const NODE_ROLES={
    ammr_dashboard_monitor:'관제용 센서·주행 상태 수집',box_approach_execution:'박스 정밀 접근 실행·정지 조건 관리',
    camera:'RGB 영상·깊이 영상 발행',camera_mount_static_transform:'차체와 카메라 사이 고정 좌표 변환',
    collision_monitor:'장애물 거리 기반 속도 제한·정지',depth_obstacle_filter:'깊이 영상에서 주행 장애물 추출',
    jdamr_base_driver:'바퀴 구동·주행 거리·배터리 수집',jdamr_depth_box_parking:'깊이 기반 박스 거리·각도 추정',
    joint_state_publisher:'로봇 관절 상태 발행',lifecycle_manager_box_approach:'접근 관련 노드 활성 상태 관리',
    robot_state_publisher:'로봇 모델의 관절·링크 좌표 변환',velocity_smoother:'속도 명령의 가감속 완화',
    ydlidar_g4_node:'G4 라이다 스캔 수집',amcl:'저장 지도 기반 위치 추정',
    map_server:'저장된 점유 지도 제공',planner_server:'목표까지 전역 경로 계산',
    controller_server:'경로 추종 속도 계산',bt_navigator:'Nav2 이동 작업·복구 흐름 관리',
    slam_toolbox:'2D 지도 생성·위치 추정',cartographer_node:'센서 기반 SLAM 궤적 추정',
    cartographer_occupancy_grid_node:'SLAM 결과를 2D 점유 지도로 변환',rtabmap:'RGB-D 기반 지도·루프 폐쇄 처리',
  };
  const TOPIC_ROLES={
    '/battery_state':'배터리 전압·잔량', '/bond':'노드 간 생존 확인',
    '/box_parking/execution_status':'정밀 접근 단계·출발 차단 사유', '/box_parking/perception_status':'박스 감지·거리·각도·관측 안정성',
    '/cmd_vel':'충돌 보호를 거친 최종 구동 명령', '/cmd_vel_nav':'주행 제어기가 요청한 속도',
    '/cmd_vel_smoothed':'가감속 완화 후 충돌 감시에 전달할 속도',
    '/collision_monitor/collision_points_marker':'충돌 판단에 사용한 점의 시각화',
    '/collision_monitor_state':'충돌 감시의 정지·감속 판단',
    '/depth_navigation/obstacles':'깊이 영상에서 추출한 장애물', '/depth_navigation/rays':'깊이 기반 거리 관측',
    '/depth_navigation/status':'깊이 장애물 처리 상태', '/diagnostics':'장치·노드 진단 보고',
    '/imu/data_raw':'IMU 각속도·가속도', '/imu/mag':'IMU 자기장 측정', '/joint_states':'관절 위치·속도 상태',
    '/local_costmap/published_footprint':'주행 판단에 쓰는 차체 외곽', '/map':'2D 점유 지도',
    '/navigate_to_pose/_action/status':'Nav2 목표 수행 상태', '/odom':'바퀴 기반 위치·속도 추정',
    '/parameter_events':'노드 설정값 변경 이벤트', '/plan':'전역 계획 경로', '/robot_description':'로봇 형상·링크 모델',
    '/rosout':'ROS 실행 로그', '/scan':'라이다 거리 스캔', '/slowdown_zone':'감속 판단 영역',
    '/stop_zone':'정지 판단 영역', '/tf':'시간에 따라 변하는 좌표 변환', '/tf_static':'센서 장착 등 고정 좌표 변환',
  };
  function nodeRole(name){const base=String(name).split('/').pop();return base.startsWith('_ros2cli_daemon_')?'ROS 명령 도구의 그래프 검색':NODE_ROLES[base]??'역할 미등록 · 구성 확인 필요'}
  function topicRole(name){if(TOPIC_ROLES[name])return TOPIC_ROLES[name];if(/^\/camera\/(color|depth)\/(image_raw|camera_info)$/.test(name)){const parts=name.split('/');return`${parts[2]==='color'?'RGB':'깊이'} ${parts[3]==='camera_info'?'카메라 보정값·내부 파라미터':'원본 영상'}`}if(name.endsWith('/transition_event'))return'노드 활성·비활성 전환 이벤트';return'역할 미등록 · 메시지 정의 확인 필요'}
  function graphRows(graph,query=''){
    if(!live(graph))return{nodes:[],topics:[]};
    const counts=new Map();arr(graph.node_names).forEach(v=>{const n=String(v);counts.set(n,(counts.get(n)||0)+1)});
    const match=v=>`${v.name} ${v.role}`.toLowerCase().includes(query.trim().toLowerCase());
    return{nodes:[...counts].map(([name,count])=>({name,count,role:nodeRole(name)})).filter(match),topics:arr(graph.topic_names).map(v=>({name:String(v),role:topicRole(String(v))})).filter(match)};
  }

  function table(body,values,cols,empty){body.replaceChildren();if(!values.length){const r=document.createElement('tr'),c=document.createElement('td');c.colSpan=cols.length;c.className='empty-row';c.textContent=empty;r.append(c);body.append(r);return}values.forEach(v=>{const r=document.createElement('tr');cols.forEach(col=>{const c=document.createElement('td');if(col.cls)c.className=col.cls;c.textContent=col.get(v);r.append(c)});body.append(r)})}
  function lists(system,graph){
    const rows=graphRows(graph,$('graph-search')?.value||'');
    table($('node-rows'),rows.nodes,[{cls:'path',get:v=>v.name},{cls:'role',get:v=>v.role},{cls:'num',get:v=>`${v.count}개`}],live(graph)?'검색 조건에 맞는 노드 없음':'노드 목록 미수신');
    table($('topic-rows'),rows.topics,[{cls:'path',get:v=>v.name},{cls:'role',get:v=>v.role}],live(graph)?'검색 조건에 맞는 토픽 없음':'토픽 목록 미수신');
    const dup=arr(graph.duplicates);txt('duplicate-nodes',!live(graph)?'동일 이름 관측 여부 미확인':dup.length?`동일 이름 다중 관측: ${dup.map(String).join(', ')} · 중복 실행 여부는 추가 확인 필요`:'동일 이름 다중 관측 없음');
    const box=$('service-list');box.replaceChildren();const services=arr(system.services);if(!services.length){const e=document.createElement('div');e.className='empty-row';e.textContent=live(system)?'서비스 정보 없음':'서비스 미수신';box.append(e)}else services.forEach(v=>{const r=document.createElement('div'),n=document.createElement('span'),s=document.createElement('span'),st=String(v?.state??'unknown'),running=/^(active|running)(?:\s|$)/i.test(st),failed=/^(failed|error)(?:\s|$)/i.test(st),stopped=/^(inactive|dead)(?:\s|$)/i.test(st),label=running?'실행 중':failed?'실패':stopped?'중지':'확인 불가';r.className='service';n.textContent=String(v?.name??'—');s.title=st;tag(s,live(system)?label:`지난 값 · ${label}`,live(system)?(running?'ok':failed?'danger':'warn'):'warn');r.append(n,s);box.append(r)});
    table($('process-rows'),live(system)?arr(system.top_processes):[],[{cls:'num',get:v=>String(v?.pid??'—')},{get:v=>String(v?.name??'—')},{cls:'num',get:v=>`${num(v?.cpu_pct,1)}%`},{cls:'num',get:v=>`${num(v?.memory_mb,0)} MB`}],live(system)?'프로세스 정보 없음':'프로세스 미수신');
    const errors=$('error-list');errors.replaceChildren();arr(system.errors).forEach(v=>{const li=document.createElement('li');li.textContent=typeof v==='string'?v:JSON.stringify(v);errors.append(li)})
  }
  function canvas(id){const c=$(id),b=c.getBoundingClientRect(),d=window.devicePixelRatio||1,w=Math.max(1,Math.round(b.width)),h=Math.max(1,Math.round(b.height));if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);return{x,w,h}}
  function lidarDraw(l){const{x,w,h}=canvas('lidar-canvas'),points=arr(l.points_xy_m).filter(p=>Array.isArray(p)&&finite(p[0])&&finite(p[1]));if(!live(l)||!points.length){$('lidar-empty').hidden=false;return}$('lidar-empty').hidden=true;const r=Math.max(1,Math.min(12,Math.ceil(Math.max(...points.map(p=>Math.hypot(Number(p[0]),Number(p[1]))),1)))),cx=w/2,cy=h/2,scale=Math.min(w,h)*.43/r;x.strokeStyle='#dce4ee';x.fillStyle='#53657a';x.lineWidth=1;x.font='10px system-ui';for(let m=1;m<=r;m+=Math.max(1,Math.ceil(r/4))){x.beginPath();x.arc(cx,cy,m*scale,0,Math.PI*2);x.stroke();x.fillText(`${m} m`,cx+4,cy-m*scale+12)}x.beginPath();x.moveTo(cx,8);x.lineTo(cx,h-8);x.moveTo(8,cy);x.lineTo(w-8,cy);x.stroke();x.fillStyle='#1761c4';points.forEach(p=>x.fillRect(cx-Number(p[1])*scale-1.4,cy-Number(p[0])*scale-1.4,2.8,2.8));if(l.display_frame==='base_footprint'){const left=cx-.27*scale,top=cy-.065*scale,width=.54*scale,height=.34*scale;x.fillStyle='rgba(180,35,50,.09)';x.strokeStyle='#b42332';x.lineWidth=1.5;x.fillRect(left,top,width,height);x.strokeRect(left,top,width,height)}x.fillStyle='#b42332';x.beginPath();x.arc(cx,cy,3.5,0,Math.PI*2);x.fill()}

  function projection(map,wx,wy,d){const o=obj(map.origin??map.metadata?.origin);if(![wx,wy,o.x_m,o.y_m,o.yaw_deg,map.resolution_m,map.width,map.height].every(finite))return null;const a=Number(o.yaw_deg)*Math.PI/180,dx=Number(wx)-Number(o.x_m),dy=Number(wy)-Number(o.y_m),lx=Math.cos(a)*dx+Math.sin(a)*dy,ly=-Math.sin(a)*dx+Math.cos(a)*dy;return{x:d.x+lx/Number(map.resolution_m)*d.sx,y:d.y+(Number(map.height)-ly/Number(map.resolution_m))*d.sy}}
  function mapDraw(map,nav){const{x,w,h}=canvas('map-canvas'),o=obj(map.origin??map.metadata?.origin),ok=map.available===true&&S.mapImage?.complete&&S.mapImage.naturalWidth>0&&[o.x_m,o.y_m,o.yaw_deg,map.resolution_m,map.width,map.height].every(finite);if(!ok){$('map-empty').hidden=false;return}$('map-empty').hidden=true;const q=Math.min(w/S.mapImage.naturalWidth,h/S.mapImage.naturalHeight),d={x:(w-S.mapImage.naturalWidth*q)/2,y:(h-S.mapImage.naturalHeight*q)/2,w:S.mapImage.naturalWidth*q,h:S.mapImage.naturalHeight*q};d.sx=d.w/Number(map.width);d.sy=d.h/Number(map.height);x.imageSmoothingEnabled=false;x.drawImage(S.mapImage,d.x,d.y,d.w,d.h);const path=obj(nav.path),pts=live(path)&&path.frame_id===map.frame_id?arr(path.points_xy_m).map(p=>projection(map,p?.[0],p?.[1],d)).filter(Boolean):[];if(pts.length>1){x.strokeStyle='#1761c4';x.lineWidth=2.5;x.beginPath();x.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>x.lineTo(p.x,p.y));x.stroke()}const loc=obj(nav.localization);if(live(loc)&&loc.frame_id===map.frame_id){const p=projection(map,loc.x_m,loc.y_m,d);if(p){x.save();x.translate(p.x,p.y);x.rotate((-Number(loc.yaw_deg)+Number(o.yaw_deg))*Math.PI/180);x.fillStyle='#b42332';x.beginPath();x.moveTo(9,0);x.lineTo(-7,-6);x.lineTo(-7,6);x.closePath();x.fill();x.restore()}}}
  function mapLoad(map,nav){const o=obj(map.origin??map.metadata?.origin),ok=map.available===true&&map.version!=null&&[o.x_m,o.y_m,o.yaw_deg].every(finite);if(!ok){S.mapImage=null;S.mapKey='';mapDraw(map,nav);return}const key=String(map.version);if(S.mapKey===key&&S.mapImage){mapDraw(map,nav);return}S.mapKey=key;const im=new Image();S.mapImage=im;im.onload=()=>mapDraw(map,nav);im.onerror=()=>{if(S.mapImage===im){S.mapImage=null;$('map-empty').hidden=false}};im.src=`/api/map.png?version=${encodeURIComponent(key)}`}

  function render(data){
    const system=obj(data.system),server=obj(data.server),graph=obj(data.graph),nav=obj(data.navigation),depth=obj(data.depth),color=obj(data.color),lidar=obj(data.lidar),motion=obj(data.motion),odom=obj(motion.odom),command=obj(motion.cmd),requested=obj(motion.requested_cmd),input=obj(motion.input_cmd),battery=obj(data.battery),imu=obj(data.imu),depthNav=obj(data.depth_navigation),execution=obj(nav.execution),perception=obj(nav.perception),collision=obj(nav.collision),goal=obj(nav.goal),map=obj(nav.map),loc=obj(nav.localization),throttle=obj(system.throttle);
    $('status-ribbon').classList.add('is-live');$('connection').className='ribbon-value';txt('connection',`연결됨 · ${age(system)}`);const drive=live(execution)?ko(execution.state):live(goal)?ko(goal.status):'확인 불가',blockers=live(execution)?arr(execution.blockers):[],collisionLabel=live(collision)?ko(collision.action):live(execution)?ko(execution.collision_monitor_state):'';txt('drive-state',drive);txt('block-reason',blockers.length?blockers.map(blockerLabel).join(' · '):collisionLabel?`${collisionLabel}${live(collision)&&collision.polygon?` · 영역 ${scalar(collision.polygon)}`:''}`:'차단 근거 미수신');$('block-reason').title=blockers.join('\n');$('drive-state').className=`ribbon-value${/차단|실패|정지|중단/.test(drive)?' danger':''}`;$('block-reason').className=`ribbon-value${blockers.length||/정지/.test(collisionLabel)?' danger':''}`;
    txt('hostname',live(system)?system.hostname:'—');txt('uptime',live(system)?`가동 시간 ${duration(system.uptime_s)}`:'가동 시간 —');txt('cpu',unit(system,system.cpu_pct,'%',0));txt('cpu-detail',live(system)?`${num(system.cpu_count,0)} cores · ${num(system.cpu_freq_mhz,0)} MHz`:'— cores · — MHz');txt('temperature',unit(system,system.cpu_temp_c,'°C',1));txt('throttle',throttle.available&&live(system)?arr(throttle.current).join(', ')||'스로틀 없음':'스로틀 확인 불가');txt('memory',unit(system,system.memory_pct,'%',0));txt('memory-detail',live(system)?`${num(system.memory_used_mb,0)} / ${num(system.memory_total_mb,0)} MB`:'— / — MB');txt('load',live(system)?`${num(system.load_1m,2)} / ${num(system.load_5m,2)} / ${num(system.load_15m,2)}`:'—');txt('disk',unit(system,system.disk_pct,'%',0));txt('disk-detail',live(system)?`여유 ${num(system.disk_free_gb,1)} GB`:'여유 — GB');txt('ros-count',live(graph)?`${num(graph.nodes,0)} nodes`:'—');txt('ros-topics',live(graph)?`토픽 ${num(graph.topics,0)}`:'토픽 —');const resources=document.querySelectorAll('.resource');resources.forEach(e=>e.classList.remove('warn','danger'));if(live(system)&&finite(system.cpu_temp_c)){if(Number(system.cpu_temp_c)>=80)resources[2].classList.add('danger');else if(Number(system.cpu_temp_c)>=70)resources[2].classList.add('warn')}if(live(system)&&finite(system.memory_pct)&&Number(system.memory_pct)>=90)resources[3].classList.add('warn');if(live(system)&&finite(system.disk_pct)){if(Number(system.disk_pct)>=90)resources[5].classList.add('danger');else if(Number(system.disk_pct)>=80)resources[5].classList.add('warn')}
    txt('map-meta',map.available?`${map.frame_id??'—'} · ${num(map.known_pct,1)}% 확인 · ${age(map)}`:'지도 미수신');txt('localization-meta',live(loc)?`위치 ${num(loc.x_m,2)}, ${num(loc.y_m,2)} m · ${num(loc.yaw_deg,1)}° · ${age(loc)}`:'위치 미수신');txt('odom',cmd(odom,true));txt('cmd',cmd(command,true));txt('requested-cmd',cmd(requested,true));txt('input-cmd',cmd(input,true));
    txt('lidar-meta',live(lidar)?`${num(lidar.fps,1)} fps · ${age(lidar)}`:age(lidar));txt('left-range',unit(lidar,lidar.left_m,'m',2));txt('front-range',unit(lidar,lidar.front_m,'m',2));txt('right-range',unit(lidar,lidar.right_m,'m',2));txt('lidar-points',live(lidar)?num(lidar.valid_points,0):'—');txt('lidar-note',live(lidar)&&lidar.display_frame==='base_footprint'?'base_footprint · 하부 차체 기준 [-0.275, 0.065] × [-0.27, 0.27] m · 안전 여유가 아닙니다':`${lidar.display_frame??'좌표 원점 미수신'} · 차체 외곽은 표시하지 않음`);
    txt('camera-meta',`RGB ${age(color)} · Depth ${age(depth)}`);txt('center-depth',unit(depth,depth.center_m,'m',2));txt('nearest-depth',unit(depth,depth.nearest_m,'m',2));txt('valid-depth',unit(depth,depth.valid_pct,'%',1));txt('depth-shape',live(depth)&&depth.width?`${depth.width}×${depth.height} · ${num(depth.fps,1)} fps`:'—');
    txt('goal-status',live(goal)?ko(goal.status):'확인 불가');txt('goal-age',age(goal));txt('execution',live(execution)?`${ko(execution.state)} · ${age(execution)}`:'—');txt('perception',perceptionText(perception));txt('collision',live(collision)?`${ko(collision.action)} · ${age(collision)}`:'—');txt('depth-nav',live(depthNav)?`${ko(depthNav.state??depthNav.status)} · ${age(depthNav)}`:'—');txt('battery',live(battery)?`${unit(battery,battery.voltage_v,'V',1)} · ${age(battery)}`:'—');txt('imu',live(imu)?`${unit(imu,imu.angular_z_rps,'rad/s',3)} · ${age(imu)}`:'—');txt('graph-meta',`Domain ${server.ros_domain_id??'—'} · 검색 ${server.discovery_range??'—'} · RMW ${server.rmw_implementation??'미지정(기본값)'}`);txt('ros-domain',server.ros_domain_id??'—');txt('discovery-range',server.discovery_range??'—');txt('rmw-implementation',server.rmw_implementation??'미지정(기본값)');txt('swap',unit(system,system.swap_pct,'%',0));txt('throttle-current',throttle.available&&live(system)?arr(throttle.current).join(', ')||'없음':'확인 불가');txt('throttle-history',throttle.available&&live(system)?arr(throttle.historical).join(', ')||'없음':'확인 불가');
    if(!live(collision)&&live(execution))txt('collision',`${ko(execution.collision_monitor_state)} · 접근기 상태`);
    $('odom').title=live(odom)?`odom 위치 ${num(odom.x_m,3)}, ${num(odom.y_m,3)} m · 방향 ${num(odom.yaw_deg,1)}°`:'주행 측정 미수신';
    lists(system,graph);lidarDraw(lidar);mapLoad(map,nav);streams(color,depth)
  }
  function disconnected(){S.connected=false;S.data=null;const blank={system:{},graph:{},navigation:{},depth:{},color:{},lidar:{},motion:{},battery:{},imu:{},depth_navigation:{}};render(blank);$('status-ribbon').classList.remove('is-live');$('connection').className='ribbon-value danger';txt('connection','서버 연결 끊김');txt('drive-state','확인 불가');txt('block-reason','서버 상태 미수신');stopStreams()}
  async function poll(){clearTimeout(S.timer);if(S.inflight){S.repoll=true;return}S.inflight=true;const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch('/api/state',{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(r.status);const data=await r.json();S.connected=true;S.data=data;render(data)}catch(_){disconnected()}finally{clearTimeout(t);S.inflight=false;const delay=S.repoll?0:(document.hidden?HIDDEN_MS:VISIBLE_MS);S.repoll=false;S.timer=setTimeout(poll,delay)}}
  function stopStreams(){Object.values(S.streamTimers).forEach(clearTimeout);S.streamTimers={};['color-feed','depth-feed'].forEach(id=>$(id).removeAttribute('src'))}
  function stream(key,id,path,isLive){const im=$(id);if(document.hidden||!isLive||!S.connected||Date.now()<S.streamBlocked[key]){im.removeAttribute('src');return}if(!im.getAttribute('src'))im.src=`${path}?t=${Date.now()}`}
  function streams(color,depth){stream('color','color-feed','/stream/color.mjpg',live(color));stream('depth','depth-feed','/stream/depth.mjpg',live(depth))}
  function retryStream(key,id){if(document.hidden||!S.connected)return;const delay=S.streamRetry[key];S.streamBlocked[key]=Date.now()+delay;$(id).removeAttribute('src');clearTimeout(S.streamTimers[key]);S.streamTimers[key]=setTimeout(()=>{S.streamRetry[key]=Math.min(delay*2,30000);S.streamBlocked[key]=0;if(S.data)streams(obj(S.data.color),obj(S.data.depth))},delay)}
  function visibility(){clearTimeout(S.timer);if(document.hidden){stopStreams();if(S.inflight)S.repoll=true;else S.timer=setTimeout(poll,HIDDEN_MS)}else{S.streamRetry={color:1000,depth:1000};S.streamBlocked={color:0,depth:0};poll();if(S.data)streams(obj(S.data.color),obj(S.data.depth))}}
  loadPrefs();$('graph-search')?.addEventListener('input',()=>{if(S.data)lists(obj(S.data.system),obj(S.data.graph))});$('view-mode').addEventListener('change',()=>{$('app-shell').classList.toggle('compact',$('view-mode').value==='compact');savePrefs();if(S.data)render(S.data)});[['color','color-feed'],['depth','depth-feed']].forEach(([key,id])=>{$(id).addEventListener('error',()=>retryStream(key,id));$(id).addEventListener('load',()=>{S.streamRetry[key]=1000;S.streamBlocked[key]=0})});document.addEventListener('visibilitychange',visibility);window.addEventListener('resize',()=>{if(S.data){lidarDraw(obj(S.data.lidar));mapDraw(obj(S.data.navigation?.map),obj(S.data.navigation))}});setInterval(()=>txt('clock',new Date().toLocaleTimeString('ko-KR',{hour12:false})),1000);txt('clock',new Date().toLocaleTimeString('ko-KR',{hour12:false}));poll();
})();
